// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  APEX DM — runtime/fake_events.rs                                        ║
// ║  All events that flow through the application. UI callbacks dispatch     ║
// ║  these; the simulation loop processes them each tick.                    ║
// ╚══════════════════════════════════════════════════════════════════════════╝

#[derive(Debug, Clone)]
pub enum AppEvent {
    // ── Download lifecycle ──────────────────────────────────────────────────
    AddDownload    { url: String, name: String, conns: String },
    AddScheduled   { url: String, name: String, sched_time: String },
    PauseDownload  (String),
    ResumeDownload (String),
    DeleteDownload (String),
    RetryDownload  (String),
    OpenFolder     (String),
    MoveToQueue    (String),

    // ── Bulk operations ─────────────────────────────────────────────────────
    PauseAll,
    ResumeAll,
    DeleteAll,
    DeleteSelected,

    // ── UI state ────────────────────────────────────────────────────────────
    SelectRow      { id: String, shift: bool, control: bool },
    MoveSelectedToQueue,
    SelectPrev { shift: bool, control: bool },
    SelectNext { shift: bool, control: bool },
    SelectPageUp { shift: bool, control: bool },
    SelectPageDown { shift: bool, control: bool },
    ToggleSelected,
    ShowChunkDetails(String),
    SetFilter      (String),
    SearchChanged  (String),
    ToggleRTL,
    SaveSettings {
        path:                String,
        launch_on_startup:   bool,
        start_minimized:     bool,
        auto_update:         bool,
        send_telemetry:      bool,
        ask_download_path:   bool,
        create_subfolder:    bool,
        open_folder_on_done: bool,
        on_complete_action:  i32,
        max_simultaneous:    i32,
        max_conns:           String,
        retry_failed:        bool,
        retry_count:         i32,
        retry_delay:         i32,
        skip_duplicates:     bool,
        duplicate_action:    i32,
        verify_integrity:    bool,
        auto_extract:        bool,
        use_proxy:           bool,
        proxy_type:          i32,
        proxy_auth:          bool,
        bind_interface:      i32,
        timeout_secs:        i32,
        force_ipv4:          bool,
        server_rate_limit:   bool,
        remember_creds:      bool,
        user_agent:          i32,
        global_dl_limit:     bool,
        global_ul_limit:     bool,
        speed_profile:       i32,
        slow_speed_kbps:     i32,
        scheduler_enabled:   bool,
        sched_speed_mode:    i32,
        capture_chrome:      bool,
        capture_firefox:     bool,
        capture_edge:        bool,
        capture_brave:       bool,
        capture_opera:       bool,
        capture_all:         bool,
        capture_confirm:     bool,
        capture_video:       bool,
        min_capture_mb:      i32,
        notif_done:          bool,
        notif_fail:          bool,
        notif_pause:         bool,
        notif_disk:          bool,
        notif_new:           bool,
        sound_done:          bool,
        sound_type:          i32,
        do_not_disturb:      bool,
        theme_mode:          i32,
        font_size:           i32,
        taskbar_progress:    bool,
        speed_graph:         bool,
        compact_rows:        bool,
        show_chunks:         bool,
        animations:          bool,
        app_lock:            bool,
        biometric:           bool,
        lock_timeout_mins:   i32,
        av_scan:             bool,
        block_malware:       bool,
        warn_exe:            bool,
        https_only:          bool,
        verify_ssl:          bool,
        history_retention:   i32,
        clear_on_exit:       bool,
        workers:             String,
        chunk_size_kb:       i32,
        buffer_mb:           i32,
        disk_write_strategy: i32,
        rest_api:            bool,
        daemon_host:         String,
        daemon_port:         String,
        log_level:           i32,
        max_log_mb:          i32,
        language:            i32,
        date_fmt:            i32,
        num_fmt:             i32,
    },

    // ── Internal / runtime ──────────────────────────────────────────────────
    SchedulerTriggered,
    ProgressUpdated,

    // ── Notification ────────────────────────────────────────────────────────
    /// Dismiss the current toast notification immediately (user clicked ✕)
    DismissNotification,

    /// Open a URL or path in the system default application
    OpenUrl(String),

    /// Open the logs folder in the system file manager
    OpenLogsFolder,
}
