export global Spacing {
    out property <length> xs:   4px;
    out property <length> sm:   6px;
    out property <length> md:   8px;
    out property <length> lg:   12px;
    out property <length> xl:   16px;
    out property <length> xxl:  24px;

    out property <length> radius-sm:  2px;
    out property <length> radius-md:  4px;
    out property <length> radius-lg:  8px;
    out property <length> radius-xl: 10px;

    out property <length> sidebar-width:    196px;
    out property <length> titlebar-height:   32px;
    out property <length> toolbar-height:    46px;
    out property <length> filterbar-height:  30px;
    out property <length> colheader-height:  22px;
    out property <length> statusbar-height:  20px;
    out property <length> row-height:        28px;
}
